### ISSUE TITLE
Doesn't pick up alpine base image

### ISSUE THREAD

**Issue by timmo001** [ludeeus/dockerfile-updater#11]
So the latest as of now for alpine is `3.11.5` but my dockerfile is using `3.11.3`.

Looking at the way it pulls the latest image, this should be correct:

https://registry.hub.docker.com/v2/repositories/library/alpine/tags

![Screenshot_20200419_141646](https://user-images.githubusercontent.com/28114703/79688766-6ad7b880-8248-11ea-87ec-f9057f56466d.png)

but when I run the action on the hour, I get no updates.

### Dockerfile

https://github.com/timmo001/notes/blob/master/Dockerfile

### Logs

https://github.com/timmo001/notes/runs/599443926?check_suite_focus=true

_Nice log messages btw :smile:_

**Comment by timmo001** [comment]
I don't think there is anything that would be different with my dockerfile, but I also didn't get an update for git which has recently updated which I had to manually update for my builds to continue.

Maybe a solution would be to add verbose logging and output everything that could be of use to diagnose the issue first

**Comment by ludeeus** [comment]
With your structure it will not pick up the base:
```
ARG BUILD_FROM=alpine:3.11.3
# hadolint ignore=DL3006
FROM ${BUILD_FROM}
```

Currently, it only looks for `FROM` for the base.

As for your `git` package, it looks ok, so there must be a bug for that :/

**Comment by ludeeus** [comment]
Actually, from your logs it didn't check any of the packages, I tried your Dockerfile, and it scans for all of them in my test.

**Comment by ludeeus** [comment]
<https://github.com/timmo001/notes/pull/20> 
<https://github.com/timmo001/notes/runs/599997381?check_suite_focus=true>
Both issues fixed, I will release a new version of the action tomorrow.

**Comment by timmo001** [comment]
Brilliant. Thanks, @ludeeus :+1:
