### ISSUE TITLE
Action downgrading versions rather than upgrading on Alpine Edge

### ISSUE THREAD

**Issue by modem7** [ludeeus/dockerfile-updater#138]
## The problem
Have run the script, and it seems to want to downgrade from the latest alpine:edge package to a quite outdated version.
https://github.com/modem7/Dnscrypt-Proxy/pull/4

## Environment

- Link to action configuration: https://github.com/modem7/Dnscrypt-Proxy/blob/master/.github/workflows/update_dockerfiles.yml
- Link to action run: https://github.com/modem7/Dnscrypt-Proxy/actions/runs/1445170254

## Additional information
Latest version: https://pkgs.alpinelinux.org/packages?name=dnscrypt-proxy&branch=edge

**Comment by ludeeus** [comment]
This currently not work with `edge`

**Comment by modem7** [comment]
May I ask what's currently stopping edge working?

**Comment by ludeeus** [comment]
There is no logic to handle different branches, so it always assumes the latest version (3.14 now)

**Comment by modem7** [comment]
Just an FYI, 3.15 has been released

**Comment by pyunramura** [comment]
Same issue here on Alpine 3.15. [Link to PR](https://github.com/pyunramura/microw/pull/14)
