### ISSUE TITLE
Updater trying to downgrade packages on alpine v3.12.0

### ISSUE THREAD

**Issue by timmo001** [ludeeus/dockerfile-updater#29]
Not sure what is going on here. Is alpine 3.12 supported?

https://github.com/timmo001/home-panel/pull/1204

Dockerfile:

https://github.com/timmo001/home-panel/blob/master/Dockerfile

**Comment by ludeeus** [comment]
> Is alpine 3.12 supported?

Now it is

**Comment by timmo001** [comment]
Brilliant. Thanks @ludeeus :smiley:
